"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0&=zr+840=mtwc^e=g88cs&4_z7y&(&=v^=28_cf-28)a&k)qf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'catalog',
    'bookshelf',
    'relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# --- AJOUTE CECI À LA FIN DE settings.py ---

# Où aller après une connexion réussie
LOGIN_REDIRECT_URL = '/relations/books/' # Va à la liste des livres

# Où aller après une déconnexion réussie
LOGOUT_REDIRECT_URL = '/relations/login/' # Retourne à la page de login
# ÉTAPE 2: Dire à Django d'utiliser notre nouveau modèle
AUTH_USER_MODEL = 'relationship_app.CustomUser'

# Configuration pour le champ ImageField (profile_photo)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
AUTH_USER_MODEL = 'bookshelf.CustomUser'
# ... (tout le reste de ton settings.py)

# --- TÂCHE DE SÉCURITÉ (Étape 1 & 4) ---
# NOTE: DEBUG est réglé sur True pour le développement.
# En production, mettez TOUJOURS DEBUG = False
# DEBUG = True 

# Assure-toi que SecurityMiddleware est activé (il l'est par défaut)
# 'django.middleware.security.SecurityMiddleware',

# Étape 1: Paramètres de sécurité du navigateur
# (Nécessite que 'django.middleware.security.SecurityMiddleware' soit dans MIDDLEWARE)

# Empêche le navigateur d'essayer de "deviner" le type de contenu (protège contre XSS)
SECURE_CONTENT_TYPE_NOSNIFF = True

# Active le filtre XSS intégré du navigateur
SECURE_BROWSER_XSS_FILTER = True

# Empêche ton site d'être affiché dans un <iframe> (protège contre le clickjacking)
X_FRAME_OPTIONS = 'DENY'

# Étape 4: Content Security Policy (CSP)
# Une couche de sécurité supplémentaire contre XSS.
# Ceci dit au navigateur: "N'exécute que du code venant de ma propre origine ('self')"
# (Nécessite 'django.middleware.security.SecurityMiddleware')
SECURE_HSTS_SECONDS = 3600 # (Active HSTS - optionnel mais recommandé)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Étape 1 (suite): Sécurité des Cookies (à mettre à True en production HTTPS)
# Pour les tests ALX, nous les laissons à False, mais en production ils seraient à True.
# CSRF_COOKIE_SECURE = True  # (Nécessite HTTPS)
# SESSION_COOKIE_SECURE = True # (Nécessite HTTPS)

# --- Fin des paramètres de sécurité ---
